import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Banner from '../components/banner'
import Card from '../components/card'
import coffeeStoresData from '../data/coffee-stores.json'

export async function getStaticProps(context) {
  return {
    props: {
      coffeeStores: coffeeStoresData
    }, // will be passed to the page component as props
  }
}

export default function Home(props) {
  const handleOnBannerBtnClick = () => {
    console.log('Hi, banner button');
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur ☕</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <Banner 
        buttonText={'View stores nearby'}
        handleOnClick={handleOnBannerBtnClick}
      ></Banner>
      </main>

      <div className={styles.heroImage}>
        <Image src={'/static/hero-image.png'} alt='hero-image' width={1600} height={900}></Image>
      </div>

      {
        props.coffeeStores.length > 0 && 
        <>
          <h2 className={styles.heading2}>Stores near you</h2>
          <div className={styles.cardLayout}>
          { 
                    props.coffeeStores.map((store, index) => (
                    <Card 
                    key={store.id}
                    className={styles.card}
                    name={store.name}
                    imgUrl={store.imgUrl}
                    href={`/coffee-store/${store.id}`}
                  />
                ))                   
            }
            </div>
        </>
      }

    </div>
  )
}
