import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Banner from '../components/banner'

export default function Home() {

  const handleOnBannerBtnClick = () => {
    console.log('Hi, banner button');
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur ☕</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <Banner 
        buttonText={'View stores nearby'}
        handleOnClick={handleOnBannerBtnClick}
      ></Banner>
      </main>

      <div className={styles.heroImage}>
        <Image src={'/static/hero-image.png'} alt='hero-image' width={1600} height={900}></Image>
      </div>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
